#!/bin/bash

#error
function error(){
if [ -e $o ]; then
echo "No wireles card"
else
sleep 2
bash evil
fi
}

echo "Choose your interface"
echo
echo "1. wlan0 "
echo "2. wlan1 "
echo
echo "MonsterEvil#"
read pil

if [ $pil = "2" ]; then
	ip link set wlan1 down && iw wlan1 set monitor control && ip link set wlan1 up > /dev/null 2>&1
	bash mon
	else
	error
fi
