#!/bin/bash
kill="killall hostapd" 
IP="192.168.1.1"
IP2="192.168.1.0"
WIFI="wlan0"

#iptables
function iptables(){
ifconfig $WIFI up
ifconfig $WIFI $IP netmask 255.255.255.0

route add -net $IP2 netmask 255.255.255.0 gw $IP
sysctl -w net.ipv4.ip_forward=1 > /dev/null 2&>1

iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain
iptables -P FORWARD ACCEPT

iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination $IP:80
iptables -t nat -A PREROUTING -p tcp --dport 443 -j DNAT --to-destination $IP:443
iptables -A INPUT -p tcp --sport 443 -j ACCEPT
iptables -A OUTPUT -p tcp --dport 443 -j ACCEPT
iptables -t nat -A POSTROUTING -j MASQUERADE

}

$kill > /dev/null 2&>1
iptables
